version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'queue_bot'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src
    env_file:
      - .env